[tool.black]
line-length = 180

[tool.ruff]
# D: pydocstyle
# E: pycodestyle errors
# F: pyflakes
# I: isort
# N: pep8 naming
# W: pycodestyle warnings
lint.select = ["D", "E", "F", "I", "N", "W"]

# D203: OneBlankLineBeforeClass (203 and D213 are mutually exclusive)
# D213: MultiLineSummarySecondLine (D212 and D213 are mutually exclusive)
# E501: line-too-long (Formatting handled by black)
# D417: DocumentAllArguments (may be bugged)
lint.ignore = ["D203", "D213","E501", "D417"]
