name: CI FORMAT & LINT - Code

on: [push]

jobs:
###############################################################
################### C++ Formatting & Linting ##################
###############################################################
  format-lint-cpp:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_BINARY_CACHE: C:\vcpkg_cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # Setup vcpkg and cache the packages
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "8eb57355a4ffb410a2e94c07b4dca2dffbee8e50"
          runVcpkgInstall : true

        # Generate project & copy settings
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Generate project
        run: |
          cmake --preset dev_vc143
          cp Folder.DotSettings out/build-spark-msvc-vs22/SPARK.sln.DotSettings
        
      - name: Cleanup Code
        uses: ArturWincenciak/ReSharper_CleanupCode@v2.0
        with:
          solution: "out/build-spark-vs22/SPARK.sln"
          fail_on_reformat_needed: "yes"
          jb_cleanup_code_arg: "--profile=\"SPARK CI Cleanup\""

###############################################################
################# Python Formatting & Linting #################
###############################################################
  format-lint-python:
    runs-on: ubuntu-latest
    container: tracto/spark-python-tools:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format
        run: |
          black --check --diff --color .

      - name: Lint
        run: |
          ruff .

###############################################################
####################### Commit Linting ########################
###############################################################
  commit-lint:
    runs-on: ubuntu-latest
    container: tracto/spark-python-tools:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Commits
        run: |
          git config --global --add safe.directory /__w/spark/spark
          python .github/scripts/commit-linter.py repository . origin/main
