name: CI FORMAT & LINT - Code

on: [push]

jobs:
###############################################################
######################## C++ Formatting #######################
###############################################################
  format-cpp:
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_BINARY_CACHE: C:\vcpkg_cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        # Setup vcpkg and cache the packages
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "501db0f17ef6df184fcdbfbe0f87cde2313b6ab1"
          runVcpkgInstall : true

        # Generate project
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Generate project
        run: |
          cmake --preset dev_vc143
        
      - name: Cleanup Code
        uses: ArturWincenciak/ReSharper_CleanupCode@v2.0
        with:
          solution: "out/build-spark-vs22/SPARK.sln"
          fail_on_reformat_needed: "yes"
          jb_cleanup_code_arg: "--settings=Folder.DotSettings --profile=\"Built-in: Full Cleanup\""

###############################################################
###################### Python Formatting ######################
###############################################################
  format-lint-python:
    runs-on: ubuntu-latest
    container: tracto/spark-python-tools:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Format
        run: |
          black --check --diff --color .

      - name: Lint
        run: |
          ruff .

###############################################################
####################### Commit Linting ########################
###############################################################
  commit-lint:
    runs-on: ubuntu-latest
    container: tracto/spark-python-tools:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Commits
        run: |
          git config --global --add safe.directory /__w/spark/spark
          python .github/scripts/commit-linter.py repository . origin/main
